// GLSL ES 3.00 shader sources for the watercolor simulation.
//
// Pipeline per frame (all fragment-shader passes over the sim grid):
//   1. velocity  - thin-film (lubrication) flow: water-surface slope + paper
//                  relief, Marangoni bloom term, tilt gravity, rim drift
//   2. height    - continuity: conservative upwind fluxes of h*vel
//   3. moisture  - evaporation (boosted at wash edges -> edge darkening),
//                  absorption into the capillary layer of the paper
//   4. capillary - fiber wicking; damp cells re-wetted by an advancing wet
//                  front rejoin the wet mask (backruns)
//   5. advect    - semi-Lagrangian transport + diffusion of suspended pigment
//   6. transfer  - pigment deposition onto / lifting off the paper, with
//                  per-pigment density, staining and granulation
//   7. render    - Kubelka-Munk optical compositing of 16 pigment channels
//                  over textured paper, plus wet-sheen shading
//
// Pigment state lives in PIG_TEXTURES (=4) RGBA texture pairs for suspended
// concentration and the same number for deposited: 16 pigments total, one
// channel each. The pigment-heavy shaders below are generated by JS loops so
// the pair count stays a single constant.
//
// Other state textures (RGBA16F, ping-ponged):
//   flow  : x = water height h, y = u, z = v, w = wet mask
//   sat   : x = capillary saturation, y = "was ever wet"
//   paper : static; x = surface height, y = absorbency capacity, z = fiber noise

'use strict';

const SHADERS = {};

// range helper for generating per-pair GLSL
const NP = PIG_TEXTURES;
const RP = Array.from({ length: NP }, (_, i) => i);

SHADERS.vert = `#version 300 es
layout(location=0) in vec2 aPos;
out vec2 vUV;
void main() {
  vUV = aPos * 0.5 + 0.5;
  gl_Position = vec4(aPos, 0.0, 1.0);
}`;

const COMMON = `
precision highp float;
precision highp sampler2D;
uniform vec2 uTexel;   // 1 / grid size
uniform float uDt;
in vec2 vUV;
`;

// ---------------------------------------------------------------- paper ----
SHADERS.paper = `#version 300 es
${COMMON}
uniform float uSeed;
uniform float uGrainAmp;  // mid-frequency bumps
uniform float uToothAmp;  // fine tooth
uniform float uFiberAmp;  // directional fibers
uniform float uCapBase;   // absorbency
uniform float uCapVar;
out vec4 frag;

float hash(vec2 p) {
  p = fract(p * vec2(234.34, 435.345) + uSeed);
  p += dot(p, p + 34.23);
  return fract(p.x * p.y);
}
float vnoise(vec2 p) {
  vec2 i = floor(p), f = fract(p);
  f = f * f * (3.0 - 2.0 * f);
  return mix(mix(hash(i), hash(i + vec2(1, 0)), f.x),
             mix(hash(i + vec2(0, 1)), hash(i + vec2(1, 1)), f.x), f.y);
}
float fbm(vec2 p) {
  float v = 0.0, a = 0.5;
  for (int i = 0; i < 5; i++) {
    v += a * vnoise(p);
    p = p * 2.03 + 17.7;
    a *= 0.55;
  }
  return v;
}
void main() {
  vec2 p = vUV / uTexel;
  float grain = fbm(p * 0.045);
  float tooth = fbm(p * 0.35);
  float fiberH = vnoise(vec2(p.x * 0.9, p.y * 0.08));
  float fiberV = vnoise(vec2(p.x * 0.07, p.y * 0.85));
  float flat0 = 0.5 * (1.0 - uGrainAmp - uToothAmp - uFiberAmp); // keep mean ~0.5
  float height = clamp(flat0 + uGrainAmp * grain + uToothAmp * tooth
                       + uFiberAmp * 0.5 * (fiberH + fiberV), 0.0, 1.0);
  float capacity = uCapBase + uCapVar * fbm(p * 0.02 + 91.7);
  float fibers = vnoise(p * 0.6 + 3.1);
  // w: the coarse structure alone — coarse-grained pigments (high grain
  // parameter) settle by this field, fine ones by the full tooth in x
  float coarse = clamp(0.5 + uGrainAmp * (grain - 0.5) * 1.6, 0.0, 1.0);
  frag = vec4(height, capacity, fibers, coarse);
}`;

// ---------------------------------------------------------------- splat ----
// Brush dab: adds water + suspended pigment. MRT: flow, susp0..N-1.
SHADERS.splat = `#version 300 es
${COMMON}
uniform sampler2D uFlow;
${RP.map((i) => `uniform sampler2D uSusp${i};`).join('\n')}
uniform sampler2D uPaper;
uniform vec2 uCenter;
uniform float uRadius;
uniform vec2 uAspect;
uniform float uWaterAmt;
${RP.map((i) => `uniform vec4 uPig${i};`).join('\n')}
uniform float uWetness;
uniform float uPush;
uniform float uScrub;
layout(location=0) out vec4 oFlow;
${RP.map((i) => `layout(location=${i + 1}) out vec4 oSusp${i};`).join('\n')}

void main() {
  vec4 f = texture(uFlow, vUV);
${RP.map((i) => `  vec4 g${i} = texture(uSusp${i}, vUV);`).join('\n')}
  vec4 pap = texture(uPaper, vUV);

  vec2 d = (vUV - uCenter) * uAspect;
  float r = length(d) / max(uRadius, 1e-5);
  float m = 1.0 - smoothstep(0.3, 1.0, r);

  // Dry-brush: with little water the brush only touches the raised tooth of
  // the paper; with lots of water it floods the valleys too.
  float contact = smoothstep(pap.x - 0.55, pap.x + 0.1, uWetness * 1.25 + 0.15);
  m *= mix(contact, 1.0, smoothstep(0.75, 1.0, uWetness));
  m *= 0.75 + 0.5 * pap.z;

  if (m > 0.0) {
    f.x += uWaterAmt * m;
    f.w = max(f.w, smoothstep(0.0, 0.08, m * uWaterAmt * 40.0));
    // outward shove where the dab lands on already-wet paper
    float rim = smoothstep(0.15, 0.85, r);
    f.yz += normalize(d + vec2(1e-6)) * (uPush * m * rim * f.w);
    // a clean wet brush scrubs suspended pigment off the sheet
${RP.map((i) => `    g${i} = g${i} * (1.0 - uScrub * m) + uPig${i} * m;`).join('\n')}
  }
  oFlow = f;
${RP.map((i) => `  oSusp${i} = g${i};`).join('\n')}
}`;

// ------------------------------------------------------------- velocity ----
SHADERS.velocity = `#version 300 es
${COMMON}
uniform sampler2D uFlow;
uniform sampler2D uPaper;
${RP.map((i) => `uniform sampler2D uSusp${i};`).join('\n')}
uniform float uGrav;
uniform float uPaperSlope;
uniform float uInertia;
uniform float uEdgeFlow;
uniform float uMaran;
uniform vec2 uTilt;
uniform float uMaxSpeed;
out vec4 frag;

float pigTotal(vec2 uv) {
  return ${RP.map((i) => `dot(texture(uSusp${i}, uv), vec4(1.0))`).join(' + ')};
}

// Thin-film (lubrication) flow: for a sub-millimeter paint film inertia is
// negligible, so velocity relaxes toward -mobility * grad(water surface).
void main() {
  vec4 f = texture(uFlow, vUV);
  float h = f.x;
  float w = f.w;

  vec4 fl = texture(uFlow, vUV - vec2(uTexel.x, 0.0));
  vec4 fr = texture(uFlow, vUV + vec2(uTexel.x, 0.0));
  vec4 fb = texture(uFlow, vUV - vec2(0.0, uTexel.y));
  vec4 ft = texture(uFlow, vUV + vec2(0.0, uTexel.y));

  float pl = texture(uPaper, vUV - vec2(uTexel.x, 0.0)).x;
  float pr = texture(uPaper, vUV + vec2(uTexel.x, 0.0)).x;
  float pb = texture(uPaper, vUV - vec2(0.0, uTexel.y)).x;
  float pt = texture(uPaper, vUV + vec2(0.0, uTexel.y)).x;

  float ps = uPaperSlope * 0.05;
  vec2 grad = 0.5 * vec2((fr.x + pr * ps) - (fl.x + pl * ps),
                         (ft.x + pt * ps) - (fb.x + pb * ps));

  float mob = h / (h + 0.02);
  vec2 target = -uGrav * grad * mob;

  // rim drift: evaporation at the pinned wash edge pulls interior fluid out
  vec2 gw = 0.5 * vec2(fr.w - fl.w, ft.w - fb.w);
  target += -uEdgeFlow * gw * smoothstep(0.0005, 0.01, h);

  // Marangoni flow: paint lowers surface tension, so fluid is pulled from
  // painted regions toward clean water (log-concentration per the Gibbs
  // isotherm) — this drives wet-on-wet blooms. Fibers modulate -> feathering.
  float fiber = 0.6 + 0.8 * texture(uPaper, vUV).z;
  float pc = pigTotal(vUV);
  vec2 gp = 0.5 * vec2(pigTotal(vUV + vec2(uTexel.x, 0.0)) - pigTotal(vUV - vec2(uTexel.x, 0.0)),
                       pigTotal(vUV + vec2(0.0, uTexel.y)) - pigTotal(vUV - vec2(0.0, uTexel.y)));
  target += -uMaran * fiber * (gp / (pc + 0.08)) * smoothstep(0.02, 0.08, h);

  // device tilt: only a genuinely wet film runs (drips), damp washes hold;
  // fiber modulation breaks the advancing front into fingers
  target += uTilt * smoothstep(0.025, 0.1, h) * (0.7 + 0.6 * texture(uPaper, vUV).z);

  vec2 vel = mix(target, f.yz, uInertia);
  vel *= w * smoothstep(0.0003, 0.004, h);

  float sp = length(vel);
  if (sp > uMaxSpeed) vel *= uMaxSpeed / sp;

  frag = vec4(h, vel, w);
}`;

// --------------------------------------------------------------- height ----
SHADERS.height = `#version 300 es
${COMMON}
uniform sampler2D uFlow;
uniform float uSmooth;
out vec4 frag;

void main() {
  vec4 f = texture(uFlow, vUV);
  vec4 fl = texture(uFlow, vUV - vec2(uTexel.x, 0.0));
  vec4 fr = texture(uFlow, vUV + vec2(uTexel.x, 0.0));
  vec4 fb = texture(uFlow, vUV - vec2(0.0, uTexel.y));
  vec4 ft = texture(uFlow, vUV + vec2(0.0, uTexel.y));

  // continuity dh/dt = -div(h*vel), conservative upwind face fluxes
  float uR = 0.5 * (f.y + fr.y);
  float uL = 0.5 * (f.y + fl.y);
  float vT = 0.5 * (f.z + ft.z);
  float vB = 0.5 * (f.z + fb.z);
  float fluxR = uR > 0.0 ? f.x * uR : fr.x * uR;
  float fluxL = uL > 0.0 ? fl.x * uL : f.x * uL;
  float fluxT = vT > 0.0 ? f.x * vT : ft.x * vT;
  float fluxB = vB > 0.0 ? fb.x * vB : f.x * vB;
  float h = f.x - uDt * (fluxR - fluxL + fluxT - fluxB);

  // small diffusion mimics surface tension leveling the film
  float avg = 0.25 * (fl.x + fr.x + fb.x + ft.x);
  h = mix(h, avg, uSmooth * f.w);

  frag = vec4(max(h, 0.0), f.yz, f.w);
}`;

// ------------------------------------------------------------- moisture ----
SHADERS.moisture = `#version 300 es
${COMMON}
uniform sampler2D uFlow;
uniform sampler2D uSat;
uniform sampler2D uPaper;
uniform float uEvap;
uniform float uEdgeEvap;
uniform float uAbsorb;
uniform float uSatEvap;
uniform float uWetThresh;
layout(location=0) out vec4 oFlow;
layout(location=1) out vec4 oSat;

void main() {
  vec4 f = texture(uFlow, vUV);
  vec4 s = texture(uSat, vUV);
  vec4 pap = texture(uPaper, vUV);
  float h = f.x;
  float w = f.w;

  float wavg = 0.0;
  for (int j = -1; j <= 1; j++)
    for (int i = -1; i <= 1; i++)
      wavg += texture(uFlow, vUV + vec2(float(i), float(j)) * uTexel * 2.0).w;
  wavg /= 9.0;
  float edge = clamp(w - wavg, 0.0, 1.0);

  h -= uDt * uEvap * (1.0 + uEdgeEvap * edge) * smoothstep(0.0, 0.0005, h);

  float cap = pap.y;
  float absorb = min(uAbsorb * uDt * max(cap - s.x, 0.0), max(h, 0.0));
  s.x += absorb;
  h -= absorb;
  h = max(h, 0.0);

  if (h > uWetThresh) {
    w = min(w + uDt * 6.0, 1.0);
  } else {
    float damp = smoothstep(0.05, 0.5, s.x);
    w = max(w - uDt * 0.12 * (1.0 - 0.7 * damp), 0.0);
  }
  s.x = max(s.x - uDt * uSatEvap, 0.0);
  s.y = max(s.y, w);

  // salt grains soak up nearby water and slowly dissolve while wet
  if (s.z > 0.0) {
    float soak = min(uDt * 0.0025 * s.z, h);
    h -= soak;
    s.z = max(s.z - uDt * 0.0012 * smoothstep(0.0005, 0.01, h + soak), 0.0);
  }

  oFlow = vec4(h, f.yz, w);
  oSat = s;
}`;

// ------------------------------------------------------------ capillary ----
SHADERS.capillary = `#version 300 es
${COMMON}
uniform sampler2D uFlow;
uniform sampler2D uSat;
uniform sampler2D uPaper;
uniform float uWick;
uniform float uWickThresh;
uniform float uBackrun;
layout(location=0) out vec4 oFlow;
layout(location=1) out vec4 oSat;

void main() {
  vec4 f = texture(uFlow, vUV);
  vec4 s = texture(uSat, vUV);
  float cap = texture(uPaper, vUV).y;

  float transfer = 0.0;
  float wetNbr = 0.0;
  for (int k = 0; k < 4; k++) {
    vec2 off = k == 0 ? vec2(uTexel.x, 0.0) : k == 1 ? vec2(-uTexel.x, 0.0)
             : k == 2 ? vec2(0.0, uTexel.y) : vec2(0.0, -uTexel.y);
    float sn = texture(uSat, vUV + off).x;
    vec4 fn = texture(uFlow, vUV + off);
    wetNbr = max(wetNbr, fn.w * smoothstep(0.001, 0.01, fn.x));
    if (sn > uWickThresh) transfer += max(sn - s.x, 0.0);
    if (s.x > uWickThresh) transfer -= max(s.x - sn, 0.0);
  }
  s.x = clamp(s.x + uWick * uDt * transfer, 0.0, cap * 1.2);

  // backrun: an actively wet neighbor pushing water into a damp, drying
  // region re-wets it and releases free water that shoves pigment ahead of
  // the advancing "cauliflower" front.
  float thresh = uBackrun * cap;
  if (s.x > thresh && f.w < 0.6 && wetNbr > 0.7) {
    f.w = max(f.w, 0.75);
    f.x += uDt * 0.15 * (s.x - thresh) + 0.002;
    s.x -= uDt * 0.12 * (s.x - thresh);
  }
  oFlow = f;
  oSat = s;
}`;

// --------------------------------------------------------------- advect ----
SHADERS.advect = `#version 300 es
${COMMON}
uniform sampler2D uFlow;
uniform sampler2D uSat;
${RP.map((i) => `uniform sampler2D uSusp${i};`).join('\n')}
uniform float uPigDiff;
uniform float uSaltPush;
${RP.map((i) => `layout(location=${i}) out vec4 oSusp${i};`).join('\n')}

void main() {
  vec4 f = texture(uFlow, vUV);
  vec2 back = vUV - f.yz * uDt * uTexel;

  // salt: a dissolving grain draws water toward itself and shoves pigment
  // outward, leaving the pale starburst. Active only while the wash is in
  // the damp band — too wet and the salt just dissolves, too dry and it
  // merely sits on the surface (like real salt timing).
  if (uSaltPush > 0.0) {
    vec2 e2 = uTexel * 2.0;
    vec2 gs = 0.5 * vec2(texture(uSat, vUV + vec2(e2.x, 0.0)).z - texture(uSat, vUV - vec2(e2.x, 0.0)).z,
                         texture(uSat, vUV + vec2(0.0, e2.y)).z - texture(uSat, vUV - vec2(0.0, e2.y)).z);
    float dampBand = smoothstep(0.0005, 0.004, f.x) * (1.0 - smoothstep(0.03, 0.1, f.x));
    back += gs * uSaltPush * uTexel * dampBand;
  }
${RP.map((i) => `  vec4 g${i} = texture(uSusp${i}, back);`).join('\n')}

  float mob = f.w * smoothstep(0.0005, 0.01, f.x);
  if (mob > 0.0) {
${RP.map((i) => `    vec4 avg${i} = vec4(0.0);`).join('\n')}
    for (int k = 0; k < 4; k++) {
      vec2 off = k == 0 ? vec2(uTexel.x, 0.0) : k == 1 ? vec2(-uTexel.x, 0.0)
               : k == 2 ? vec2(0.0, uTexel.y) : vec2(0.0, -uTexel.y);
      float wn = texture(uFlow, vUV + off).w;
${RP.map((i) => `      avg${i} += mix(g${i}, texture(uSusp${i}, vUV + off), wn);`).join('\n')}
    }
    float blend = uPigDiff * uDt * mob;
${RP.map((i) => `    g${i} = mix(g${i}, avg${i} * 0.25, blend);`).join('\n')}
  }
${RP.map((i) => `  oSusp${i} = g${i};`).join('\n')}
}`;

// ------------------------------------------------------------- transfer ----
// Deposition / lifting between suspension and paper (Curtis et al. 1997 §4.5,
// with rewetting on its own resolubility timescale). Split into two draws
// (suspension update, deposit update) so no pass needs more than NP MRT
// attachments — the WebGL2 guaranteed minimum is 4. Both read the same
// pre-pass state and compute identical down/up amounts.
const TRANSFER_BODY = (outs) => `#version 300 es
${COMMON}
uniform sampler2D uFlow;
uniform sampler2D uPaper;
${RP.map((i) => `uniform sampler2D uSusp${i};`).join('\n')}
${RP.map((i) => `uniform sampler2D uDep${i};`).join('\n')}
uniform vec4 uRho[${NP}];
uniform vec4 uOmega[${NP}];
uniform vec4 uGamma[${NP}];
uniform vec4 uGrain[${NP}]; // granulation size: 0 fine tooth .. 1 coarse
uniform float uSettle;
uniform float uLift;
${RP.map((i) => `layout(location=${i}) out vec4 o${i};`).join('\n')}

void main() {
  vec4 f = texture(uFlow, vUV);
  vec4 pap = texture(uPaper, vUV);
${RP.map((i) => `  vec4 g${i} = texture(uSusp${i}, vUV);\n  vec4 d${i} = texture(uDep${i}, vUV);`).join('\n')}

  float h = f.x;
  float w = f.w;
  float ph = pap.x;      // full tooth (fine structure)
  float phc = pap.w;     // coarse grain structure only

  float dtn = uDt * uSettle;
  float dryBoost = 1.0 + 8.0 * (1.0 - smoothstep(0.0, 0.004, h));
  float liftGate = uLift * uDt * w * smoothstep(0.002, 0.015, h) * (0.3 + length(f.yz) * 2.0);
  float wgate = max(w, 0.35);

${RP.map((i) => `  {
    vec4 phE = mix(vec4(ph), vec4(phc), uGrain[${i}]); // per-paint grain scale
    vec4 down = g${i} * clamp((vec4(1.0) - phE * uGamma[${i}]) * uRho[${i}] * dtn * dryBoost, 0.0, 1.0) * wgate;
    vec4 up = d${i} * clamp((vec4(1.0) + (phE - 1.0) * uGamma[${i}]) / uOmega[${i}] * liftGate, 0.0, 1.0);
    down = min(down, max(vec4(1.0) - d${i}, 0.0));
    up = min(up, max(vec4(1.0) - g${i}, 0.0));
    o${i} = ${outs === 'susp' ? `g${i} - down + up` : `d${i} + down - up`};
  }`).join('\n')}
}`;
SHADERS.transferSusp = TRANSFER_BODY('susp');
SHADERS.transferDep = TRANSFER_BODY('dep');

// --------------------------------------------------------------- render ----
SHADERS.render = `#version 300 es
${COMMON}
uniform sampler2D uFlow;
uniform sampler2D uSat;
uniform sampler2D uPaper;
${RP.map((i) => `uniform sampler2D uSusp${i};`).join('\n')}
${RP.map((i) => `uniform sampler2D uDep${i};`).join('\n')}
uniform vec3 uK[${NP * 4}];
uniform vec3 uS[${NP * 4}];
uniform vec4 uGamma[${NP}];
uniform vec4 uGrain[${NP}];
uniform vec3 uPaperColor;
uniform float uWetView; // 1 = overlay wet/satin/damp stages
out vec4 frag;

// Kubelka-Munk reflectance & transmittance of the pigment layer; K,S are
// already scaled by concentration (optical depth).
void km(vec3 K, vec3 S, out vec3 R, out vec3 T) {
  vec3 a = (K + S) / max(S, vec3(1e-6));
  vec3 b = sqrt(max(a * a - vec3(1.0), vec3(1e-8)));
  vec3 c = clamp(b * S, vec3(0.0), vec3(20.0));
  vec3 sh = sinh(c), ch = cosh(c);
  vec3 denom = a * sh + b * ch;
  R = sh / denom;
  T = b / denom;
}

float depTotal(vec2 uv) {
  return ${RP.map((i) => `dot(texture(uDep${i}, uv), vec4(1.0))`).join(' + ')};
}

void main() {
  vec4 f = texture(uFlow, vUV);
  vec4 s = texture(uSat, vUV);
  vec4 pap = texture(uPaper, vUV);
${RP.map((i) => `  vec4 g${i} = texture(uSusp${i}, vUV);\n  vec4 d${i} = texture(uDep${i}, vUV);`).join('\n')}

  // Granulating pigment piles into paper valleys; at render scale that reads
  // as optical thickness following the inverse of paper height. Each paint's
  // grain parameter picks fine tooth vs coarse structure.
${RP.map((i) => `  {
    vec4 valley = 1.0 - mix(vec4(pap.x), vec4(pap.w), uGrain[${i}]);
    d${i} *= mix(vec4(1.0), vec4(0.45) + 1.2 * valley, uGamma[${i}]);
  }`).join('\n')}

  vec3 K = vec3(0.0), S = vec3(0.0);
  float total = 0.0;
${RP.map((i) => `  {
    vec4 x = g${i} + d${i};
    K += x.x * uK[${i * 4}] + x.y * uK[${i * 4 + 1}] + x.z * uK[${i * 4 + 2}] + x.w * uK[${i * 4 + 3}];
    S += x.x * uS[${i * 4}] + x.y * uS[${i * 4 + 1}] + x.z * uS[${i * 4 + 2}] + x.w * uS[${i * 4 + 3}];
    total += dot(x, vec4(1.0));
  }`).join('\n')}

  // paper: warm white, shaded by grain relief
  vec2 e = uTexel;
  float hx = texture(uPaper, vUV + vec2(e.x, 0.0)).x - texture(uPaper, vUV - vec2(e.x, 0.0)).x;
  float hy = texture(uPaper, vUV + vec2(0.0, e.y)).x - texture(uPaper, vUV - vec2(0.0, e.y)).x;
  vec3 n = normalize(vec3(-hx * 2.2, -hy * 2.2, 1.0));
  vec3 lightDir = normalize(vec3(0.45, 0.55, 0.8));
  float lam = 0.88 + 0.12 * max(dot(n, lightDir), 0.0);
  vec3 Rpaper = uPaperColor * lam * (0.96 + 0.04 * pap.z);

  vec3 Rtot = Rpaper;
  if (total > 1e-5) {
    vec3 R, T;
    km(K, S + vec3(1e-5), R, T);
    Rtot = R + T * T * Rpaper / (vec3(1.0) - R * Rpaper);
  }

  // dried-edge line: darken where deposited pigment changes sharply (the
  // classic watercolor rim), sampled at 2-texel radius so grain-scale
  // granulation doesn't read as edges.
  vec2 e2 = uTexel * 2.0;
  float dC = depTotal(vUV);
  float rimGrad = length(vec2(depTotal(vUV + vec2(e2.x, 0.0)) - depTotal(vUV - vec2(e2.x, 0.0)),
                              depTotal(vUV + vec2(0.0, e2.y)) - depTotal(vUV - vec2(0.0, e2.y)))) * 0.5;
  float rim = clamp(rimGrad * 0.9, 0.0, 0.30) * smoothstep(0.02, 0.3, dC);
  Rtot *= 1.0 - rim;

  // wet areas look darker & glossier
  float wetvis = clamp(f.w * 0.35 + smoothstep(0.0, 0.04, f.x) * 0.55 + s.x * 0.08, 0.0, 1.0);
  Rtot *= mix(1.0, 0.89, wetvis);

  float wx = texture(uFlow, vUV + vec2(e.x, 0.0)).x - texture(uFlow, vUV - vec2(e.x, 0.0)).x;
  float wy = texture(uFlow, vUV + vec2(0.0, e.y)).x - texture(uFlow, vUV - vec2(0.0, e.y)).x;
  vec3 wn = normalize(vec3(-wx * 30.0, -wy * 30.0, 1.0));
  float spec = pow(max(dot(wn, normalize(lightDir + vec3(0.0, 0.0, 1.0))), 0.0), 60.0);
  Rtot += spec * 0.06 * smoothstep(0.002, 0.03, f.x);

  // undissolved salt grains sit as pale specks
  Rtot = mix(Rtot, vec3(0.96, 0.96, 0.94), 0.55 * smoothstep(0.3, 0.9, s.z));

  // wetness view: the digital "look for the shine" — wet (blue), satin
  // (teal), damp (amber); dry paper is untinted. This is the timing map:
  // paint into shine = soft blends, touch damp = blooms.
  if (uWetView > 0.5) {
    float wet = smoothstep(0.012, 0.05, f.x);
    float satin = smoothstep(0.0012, 0.012, f.x) * (1.0 - wet);
    float damp = max(smoothstep(0.08, 0.35, s.x), f.w * 0.6) * (1.0 - wet - satin);
    vec3 ov = vec3(0.25, 0.55, 1.0) * wet + vec3(0.2, 0.85, 0.8) * satin + vec3(1.0, 0.75, 0.25) * damp;
    float amt = clamp(wet + satin + damp, 0.0, 1.0);
    Rtot = mix(Rtot, ov, 0.4 * amt);
  }

  frag = vec4(pow(clamp(Rtot, 0.0, 1.0), vec3(1.0 / 2.2)), 1.0);
}`;

// ----------------------------------------------------------------- salt ----
// Sprinkle salt grains into sat.z. Each grain is a sparse random cell.
SHADERS.salt = `#version 300 es
${COMMON}
uniform sampler2D uSat;
uniform vec2 uCenter;
uniform float uRadius;
uniform vec2 uAspect;
uniform float uSeed;
uniform float uDensity; // fraction of cells that get a grain
out vec4 frag;

float hash2(vec2 p) {
  p = fract(p * vec2(127.1, 311.7) + uSeed);
  p += dot(p, p + 19.19);
  return fract(p.x * p.y);
}

void main() {
  vec4 s = texture(uSat, vUV);
  vec2 d = (vUV - uCenter) * uAspect;
  float r = length(d) / max(uRadius, 1e-5);
  if (r < 1.0) {
    vec2 cell = floor(vUV / uTexel / 2.0); // grains ~2 cells wide
    if (hash2(cell) > 1.0 - uDensity) s.z = min(s.z + 0.9, 1.0);
  }
  frag = s;
}`;

// ---------------------------------------------------------------- clear ----
SHADERS.clear = `#version 300 es
${COMMON}
uniform vec4 uValue;
out vec4 frag;
void main() { frag = uValue; }`;

// ----------------------------------------------------------------- copy ----
// Blit a texture (used to restore persisted deposits, resampling if the
// canvas size changed between sessions).
SHADERS.copy = `#version 300 es
${COMMON}
uniform sampler2D uTex;
out vec4 frag;
void main() { frag = texture(uTex, vUV); }`;
