#!/bin/sh
# Write js/version.js — the build id the app reports in Settings.
#
# Why a committed content hash rather than a commit SHA injected at deploy
# time: this repo's Pages site is published by TWO deployers that both fire
# on a push to main — the workflow in .github/workflows, and GitHub's own
# built-in branch builder (dynamic/pages/pages-build-deployment). Whichever
# finishes last wins. A stamp written by one of them is therefore a coin
# toss; the built-in builder publishes the branch verbatim and would serve
# an unstamped file. The stamp has to be committed so both publish the same
# thing.
#
# A hash of the source is also a better answer to the question actually
# being asked — "am I running the code that was deployed?" — than a commit
# SHA is: it changes exactly when the served files change, and two builds of
# identical code report identical ids.
#
#   tools/stamp.sh           rewrite js/version.js
#   tools/stamp.sh --check   fail if it is stale (used by CI)
set -e
cd "$(dirname "$0")/.."

sources() {
  echo index.html
  echo sw.js
  echo manifest.webmanifest
  ls js/*.js | grep -v '/version\.js$' | sort
}

hash=$(cat $(sources) | sha256sum | cut -c1-8)

if [ "$1" = "--check" ]; then
  have=$(sed -n "s/.*build: '\([^']*\)'.*/\1/p" js/version.js)
  if [ "$have" != "$hash" ]; then
    echo "js/version.js is stale: it says '$have', the source hashes to '$hash'."
    echo "Run tools/stamp.sh and commit the result."
    exit 1
  fi
  echo "js/version.js matches the source ($hash)"
  exit 0
fi

printf "// Generated by tools/stamp.sh — do not edit by hand.\n// build: a hash of the app's own source. date: when it was stamped.\nconst BUILD = { build: '%s', date: '%s' };\n" \
  "$hash" "$(date -u '+%Y-%m-%d %H:%M UTC')" > js/version.js
cat js/version.js
